// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApI5VkZ8W3IE3VhWWaVoTssVOUPwc4N1g',
    appId: '1:600976886800:web:4f030893740aab1c218e95',
    messagingSenderId: '600976886800',
    projectId: 'uni-events-72162',
    authDomain: 'uni-events-72162.firebaseapp.com',
    storageBucket: 'uni-events-72162.firebasestorage.app',
    measurementId: 'G-QRQEMKJVDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNaqbemAxVaOnY3BNK1sZZxqV43fwz06M',
    appId: '1:600976886800:android:454e5b0c41c52ccb218e95',
    messagingSenderId: '600976886800',
    projectId: 'uni-events-72162',
    storageBucket: 'uni-events-72162.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfrgTx04deQk73wAYfKuCOguqjGIlx9vU',
    appId: '1:600976886800:ios:3bf375f1d328ec7d218e95',
    messagingSenderId: '600976886800',
    projectId: 'uni-events-72162',
    storageBucket: 'uni-events-72162.firebasestorage.app',
    iosBundleId: 'com.example.uniEvents',
  );

}